environments:
  dev:
    values:
      - values/dev.yaml
      - secrets/dev-secret.yml
    valuesFromEnv:
      envNamespace: dev 
  stage:
    values:
      - values/stage.yaml
      - secrets/stage-secret.yml
    valuesFromEnv:
      envNamespace: stage 

---

releases:
  - name: nginxdemo
    chart: ./charts/nginxdemo
    namespace: "{{ .Environment.Values.envNamespace }}"
    createNamespace: true