name: Test NginxDemo

on:
  push:
    branches:
      - main

jobs:
  deployDemo:
    runs-on: self-hosted
    strategy:
      matrix:
        env: [dev, stage]

    steps:
    - uses: actions/checkout@v4

    - name: Deploy using helmfile
      run: |
        helmfile -e ${{ matrix.env }} secrets apply
