name: Test NginxDemo

on:
  push:
    branches:
      - main

jobs:
  deployDemo:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm and Helmfile
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://get.helm.sh/helm-v3.12.3-windows-amd64.zip -OutFile helm.zip
        Expand-Archive .\helm.zip -DestinationPath .
        Move-Item .\windows-amd64\helm.exe .\helm.exe
        Invoke-WebRequest -Uri https://github.com/roboll/helmfile/releases/latest/download/helmfile_windows_amd64.exe -OutFile helmfile.exe

    - name: Deploy to dev
      shell: pwsh
      run: .\helmfile.exe -e dev apply
  
    - name: Deploy to stage
      shell: pwsh
      run: .\helmfile.exe -e stage apply
