name: Test NginxDemo

on:
  push:
    branches:
      - main

jobs:
  deployDemo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group rg-aks-test --name akstest --overwrite-existing

    - name: Install Helm, Helmfile and Helmsecrets
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        curl -L -H "Accept: application/octet-stream" https://github.com/helmfile/helmfile/releases/latest/download/helmfile_linux_amd64 -o helmfile
        chmod +x helmfile
        sudo mv helmfile /usr/local/bin/
        helm plugin install https://github.com/jkroepke/helm-secrets

    - name: Deploy to Dev
      run: |
        helmfile -e dev apply

    - name: Deploy to Stage
      run: |
        helmfile -e stage apply
